## Functions to create and handle a special object allowing
## to cache the inverse of a matrix

## makeCacheMatrix: create a special matrix able to cache its inverse.
makeCacheMatrix <- function(x = matrix()) {
  inverseMatrix <- NULL
  set <- function(y) {
    x <<- y
    inverseMatrix <<- NULL
  }
  get <- function() x
  setInverse <- function(inv) inverseMatrix <<- inv
  getInverse <- function() inverseMatrix
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## cachesolve: computes the inverse of the matrix generated by makeCacheMatrix.
## If the inverse was already computed and the matrix didn't change, the inverse
## is retreived from the cache.
cacheSolve <- function(x) {
  inverseMatrix <- x$getInverse()
  if(!is.null(inverseMatrix)) {
    message("getting cached data")
    return(inverseMatrix)
  }
  data <- x$get()
  inverseMatrix <- solve(data)
  x$setInverse(inverseMatrix)
  inverseMatrix
}